import argparse


def get_args():
    parser = argparse.ArgumentParser(description="AERI baseline args")

    parser.add_argument("--local_rank", default=0, type=int)
    parser.add_argument("--name", default="aeri_base", help="experiment name")
    parser.add_argument("--seed", default=1, type=int, help="random seed")
    parser.add_argument("--output_dir", default="logs")
    parser.add_argument("--log_period", default=100, type=int)
    parser.add_argument("--eval_period", default=1, type=int)
    parser.add_argument("--val_dataset", default="test", help="evaluate on test or val split")
    parser.add_argument("--resume", default=False, action="store_true")
    parser.add_argument("--resume_ckpt_file", default="")
    parser.add_argument("--finetune_eval_mode", default="test", type=str, help="test, heldout, or none")
    parser.add_argument("--use_swanlab", default=False, action="store_true")
    parser.add_argument("--swanlab_project", default="CFAN")
    parser.add_argument("--swanlab_experiment", default="")
    parser.add_argument("--swanlab_mode", default="cloud")

    parser.add_argument("--finetune", type=str, default="pretrain/HAMbest0.pth")
    parser.add_argument("--pretrain", type=str, default="")

    parser.add_argument("--pretrain_choice", default="ViT-B/16")
    parser.add_argument("--temperature", type=float, default=0.02)
    parser.add_argument("--img_aug", default=True, action="store_true")
    parser.add_argument("--loss_names", default="base", help="training losses: base, base+id, or base+id+bridge")
    parser.add_argument("--id_loss_weight", type=float, default=1.0, help="weight for identity classification loss")
    parser.add_argument("--bridge_loss_weight", type=float, default=0.5, help="weight for detached ground-to-aerial bridge loss")
    parser.add_argument("--bridge_mode", type=str, default="plain", help="bridge loss mode: plain or gated")
    parser.add_argument("--bridge_gate_min", type=float, default=0.2, help="minimum confidence for gated bridge loss")
    parser.add_argument("--bridge_gate_tau", type=float, default=0.1, help="temperature for gated bridge confidence")
    parser.add_argument("--MLM", default=True, action="store_true", help="kept for dataset compatibility")

    parser.add_argument("--img_size", type=tuple, default=(384, 128))
    parser.add_argument("--stride_size", type=int, default=16)
    parser.add_argument("--text_length", type=int, default=77)
    parser.add_argument("--vocab_size", type=int, default=49408)

    parser.add_argument("--optimizer", type=str, default="Adam", help="SGD, Adam, or AdamW")
    parser.add_argument("--lr", type=float, default=5e-6)
    parser.add_argument("--lr2", type=float, default=5e-5)
    parser.add_argument("--lr_factor", type=float, default=5.0)
    parser.add_argument("--bias_lr_factor", type=float, default=2.0)
    parser.add_argument("--momentum", type=float, default=0.9)
    parser.add_argument("--weight_decay", type=float, default=4e-5)
    parser.add_argument("--weight_decay_bias", type=float, default=0.0)
    parser.add_argument("--alpha", type=float, default=0.9)
    parser.add_argument("--beta", type=float, default=0.999)

    parser.add_argument("--num_epoch", type=int, default=60)
    parser.add_argument("--milestones", type=int, nargs="+", default=(20, 40))
    parser.add_argument("--gamma", type=float, default=0.1)
    parser.add_argument("--warmup_factor", type=float, default=0.1)
    parser.add_argument("--warmup_epochs", type=int, default=5)
    parser.add_argument("--warmup_method", type=str, default="linear")
    parser.add_argument("--lrscheduler", type=str, default="cosine")
    parser.add_argument("--target_lr", type=float, default=0)
    parser.add_argument("--power", type=float, default=0.9)

    parser.add_argument("--dataset_name", default="AERI-PEDES", help="AERI-PEDES or another compatible dataset")
    parser.add_argument("--sampler", default="random", help="random or identity")
    parser.add_argument("--num_instance", type=int, default=4)
    parser.add_argument("--root_dir", default="/data1/Datasets/ReID/")
    parser.add_argument("--batch_size", type=int, default=64)
    parser.add_argument("--test_batch_size", type=int, default=512)
    parser.add_argument("--num_workers", type=int, default=8)
    parser.add_argument("--finetune_val_ratio", type=float, default=0.1)
    parser.add_argument("--finetune_val_seed", type=int, default=1)
    parser.add_argument("--train_samples_per_id", type=int, default=0, help="if > 0, resample k training samples per identity each epoch")
    parser.add_argument("--train_sample_strategy", type=str, default="random", help="per-id sampling strategy: random")
    parser.add_argument("--test", dest="training", default=True, action="store_false")

    return parser.parse_args()
